---
title: "ORL_run"
output: html_document
---

Data prep

```{r}
pacman::p_load(dplyr, rstan, bayestestR, loo, lubridate)

# Helper function
split_tibble <- function(tibble, column = 'col') {
  tibble %>% split(., .[,column]) %>% lapply(., function(x) x[,setdiff(names(x),column)])
}

setwd("~/Cognitive model")

# Load data including expert ratings
data = read.csv("Data/session1000_wExpertRatings.csv", row.names =  1)

# Only consider the last 3 months of the data window
data = data[between(month(data$time_first), 4, 6),]

# Count number of sessions per player
count_temp = data %>% count(profile_id) 

#Identify players with more than 100 sessions
ID_more100 = count_temp$profile_id[count_temp$n >= 100]

# Extract a subset of 100 players
ID_more100sub = sample(ID_more100, 100)

# Subset data
data2 = data %>% filter(profile_id %in% ID_more100sub)

s = length(unique(data2$profile_id)) # Number of subjects

Tsubj = data2 %>% group_by(profile_id) %>% summarise(ses_n = length(session_no)) # Number of sessions per subject
Tsubj = Tsubj$ses_n
 
tol_ses = sum(Tsubj) # 80695 total length

# Outcome
o = data2$outcome
o_scaled = o/100
o_trajec = data2$outcome/data2$sesion_length

# Win frequency
data2$win_freq = (data2$wins + data2$LDW)/data2$sesion_length  
freq = data2$win_freq

# Sign of outcome
sign = sign(o)

# Choice
x  = data2$game

# Risk score
risk = data2 %>% group_by(profile_id) %>% summarise(mean(Risk.score))
risk = risk$`mean(Risk.score)` 
```

ORL fit
```{r}
# Preapre the data
dat = list(N=tol_ses, Tsubj = Tsubj, s =s, o=o_trajec, sign= sign, x=x)

ORL_fit = stan(file = "StanModelsForModelComparison/ORL_ind.stan", data = dat, cores = 4, chains = 4, iter = 4000, warmup =  1500, thin = 2)

# Extract predictions
predictions = extract(ORL_fit, pars = c("y_pred"))
med_pred = apply(predictions$y_pred, c(2), median)

# Estimate the one-step-ahead predictive accuracy
mean(apply(predictions$y_pred, c(2), median) == x)

# Estimate switching accuracy
switch_dat= ifelse(diff(x) == 0, 0, 1) 
switch_pred = ifelse(diff(med_pred) == 0,0,1)

mean(switch_pred == switch_dat) 
mean(switch_pred) 
mean(switch_dat)

loglik=extract_log_lik(ORL_fit, parameter_name = "log_lik")

loo(loglik)

```


VSE model fit
```{r}
dat = list(N=tol_ses, Tsubj = Tsubj, s =s, o=o_trajec, x=x)

VSE_fit = stan(file = "StanModelsForModelComparison/VSE_ind.stan", data = dat, cores = 4, chains = 4, iter = 4000, warmup =  1500, thin = 2)

# Extract log likelihood 
loglik=extract_log_lik(VSE_fit, parameter_name = "log_lik", merge_chains = TRUE)
loo(loglik)

predictions = extract(VSE_fit, pars = c("y_pred"))

mean(apply(predictions$y_pred, c(2), median) == x) 

med_pred = apply(predictions$y_pred, c(2), median)

plot(x[sum(Tsubj[1:14]):sum(Tsubj[1:15])])
plot(med_pred[sum(Tsubj[1:14]):sum(Tsubj[1:15])])

switch_dat= ifelse(diff(x) == 0, 0, 1)
switch_pred = ifelse(diff(med_pred) == 0,0,1)

mean(switch_pred == switch_dat) 
mean(switch_pred) 
mean(switch_dat)

```

PVLD model fit

```{r}

dat = list(N=tol_ses, Tsubj = Tsubj, s=s, o=o_trajec, x=x)

model = stan_model("StanModelsForModelComparison/PVLD_ind.stan")

PVL_fit = vb(model, dat, tol_rel_obj = 0.001, output_samples = 999) 

predictions = extract(PVL_fit, pars = c("y_pred"))

mean(apply(predictions$y_pred, c(2), median) == x) 

med_pred = apply(predictions$y_pred, c(2), median)

plot(x[Tsubj[14]:Tsubj[15]])
plot(med_pred[Tsubj[14]:Tsubj[15]])

switch_dat= ifelse(diff(x) == 0, 0, 1)
switch_pred = ifelse(diff(med_pred) == 0,0,1)

mean(switch_pred == switch_dat) 
mean(switch_pred) 
mean(switch_dat)

loglik=extract_log_lik(PVL_fit, parameter_name = "log_lik", merge_chains = TRUE)
loo(loglik)

```

Habitual ORL fit 


```{r}
dat = list(N=tol_ses, Tsubj = Tsubj, s =s, o=o_trajec, sign = sign, x=x)

model = stan_model("StanModelsForModelComparison/ORL_HAB_ind.stan")

fit = vb(model, dat, tol_rel_obj = 0.001, output_samples = 999)

predictions = extract(fit, pars = c("y_pred"))

mean(apply(predictions$y_pred[1:999,], c(2), median) == x) 

med_pred = apply(predictions$y_pred[1:999,], c(2), median)

switch_dat= ifelse(diff(x) == 0, 0, 1)
switch_pred = ifelse(diff(med_pred) == 0,0,1)

plot(switch_dat[107:260])
plot(switch_pred[107:260])

mean(switch_pred == switch_dat) 
mean(switch_pred) 
mean(switch_dat)

loglik=extract_log_lik(fit, parameter_name = "log_lik", merge_chains = TRUE)
loo(loglik)


```

Habitual + win frequency ORL fit

```{r}
dat = list(N=tol_ses, Tsubj = Tsubj, s =s, o=o_trajec, freq= freq, x=x)

model = stan_model("StanModelsForModelComparison/ORL2_ind.stan")

fit = vb(model, dat, tol_rel_obj = 0.001, output_samples = 999)

predictions = extract(fit, pars = c("y_pred"))

mean(apply(predictions$y_pred[1:999,], c(2), median) == x) 

med_pred = apply(predictions$y_pred[1:999,], c(2), median)

switch_dat= ifelse(diff(x) == 0, 0, 1)
switch_pred = ifelse(diff(med_pred) == 0,0,1)

plot(switch_dat[107:260])
plot(switch_pred[107:260])

mean(switch_pred == switch_dat) 
mean(switch_pred) 
mean(switch_dat)

loglik=extract_log_lik(fit, parameter_name = "log_lik", merge_chains = TRUE)
loo(loglik)

```

